# Generated by Django 4.1 on 2022-12-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_group_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='factor',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
